plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.hilt.android)
}

ext {
    sdkVersion = 34
    targetsdkVersion = 34
    supportLibVersion = "1.6.8"
    playServiceVer = "20.13.1"
    retrofitVersion = "2.9.0"
    okhttpVersion = "4.12.0"
    arch_version = "2.6.2"
}

android {
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    compileSdkVersion sdkVersion

    buildToolsVersion '34.0.0'
    defaultConfig {
        vectorDrawables.useSupportLibrary = true
        applicationId "com.mukeshteckwani.astro.astroapp"
        minSdkVersion 21
        targetSdkVersion targetsdkVersion
        versionCode 1
        versionName '1.0.0'
        // Enabling multidex support.
        multiDexEnabled true
        resConfig "en"

    }
    defaultConfig {
        applicationId "com.mukeshteckwani.astro.astroapp"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        def SERVER_URL = "URL"
        def CONFIG = { k -> "\"${project.properties.get(k)}\"" }
        release {
            buildConfigField "String", SERVER_URL, CONFIG("release.server.url")
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", SERVER_URL, CONFIG("debug.server.url")
        }
    }

    flavorDimensions "default"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        dataBinding = true
        compose = true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.material
    implementation bundle.network
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.extensions
    implementation libs.firebase.auth
    implementation libs.firebase.ui.auth
    implementation libs.glide
    implementation libs.firebase.database
    annotationProcessor libs.androidx.lifecycle.compiler
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.espresso.core
    
    // Jetpack Compose
    implementation platform(libs.compose.bom)
    implementation bundle.compose
    debugImplementation libs.compose.ui.tooling
    
    // Hilt
    implementation libs.hilt.android
    kapt libs.hilt.compiler
    implementation libs.hilt.navigation.compose
    implementation libs.hilt.lifecycle.viewmodel
}

apply plugin: 'com.google.gms.google-services'