plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.kotlin.compose)
}

apply plugin: 'com.google.dagger.hilt.android'

android {
    namespace "com.mukeshteckwani.astro.astroapp"

    compileSdk 37

    defaultConfig {
        applicationId "com.mukeshteckwani.astro.astroapp"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
        multiDexEnabled true
        resourceConfigurations += ['en']
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        def SERVER_URL = "URL"
        def CONFIG = { k -> "\"${project.properties.get(k)}\"" }
        release {
            buildConfigField "String", SERVER_URL, CONFIG("release.server.url")
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", SERVER_URL, CONFIG("debug.server.url")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    lint {
        checkReleaseBuilds = false
        abortOnError = false
    }
}

dependencies {
    implementation libs.bundles.network
    implementation libs.androidx.lifecycle.runtime
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.kotlinx.coroutines.android
    implementation libs.firebase.auth
    implementation libs.firebase.ui.auth

    implementation libs.room.runtime
    implementation libs.room.ktx
    ksp libs.room.compiler
    implementation libs.datastore.preferences

    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose
    implementation libs.compose.material.icons.extended
    implementation libs.bundles.nav3
    implementation libs.coil.compose
    implementation libs.androidx.paging.runtime
    implementation libs.androidx.paging.compose
    debugImplementation libs.compose.ui.tooling

    implementation libs.hilt.android
    implementation libs.hilt.navigation.compose
    ksp libs.hilt.compiler

    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.runner
}

apply plugin: 'com.google.gms.google-services'
